== artifacts{zwsp}.config{zwsp}.agenix{zwsp}.flakeStoreDir

Path reference where encrypted secrets are stored for agenix{zwsp}. This is used to to populate ``age{zwsp}.secrets``{zwsp}.



__Type:__ absolute path



__Example:__

----
{
  flakeStoreDir = inputs.my-secrets;
  flakeStoreDir = ./secrets;
};

----



== artifacts{zwsp}.config{zwsp}.agenix{zwsp}.identityPaths



path to the identities to decrypt the secrets at runtime



__Type:__ list of string



__Example:__

----
[
  "~/.ssh/id_ed25519"
]
----



== artifacts{zwsp}.config{zwsp}.agenix{zwsp}.publicUserKeys



public key used to encrypt secrets for this host



__Type:__ list of string



__Default:__ ``{startsb} {endsb}``



== artifacts{zwsp}.config{zwsp}.agenix{zwsp}.storeDir



Path to the secrets store where agenix backend will serialize secrets to{zwsp}.



__Type:__ string



__Default:__ ``{quot}secrets{quot}``



__Example:__ ``{quot}$HOME/nixos-secrets{quot}``



== artifacts{zwsp}.config{zwsp}.agenix{zwsp}.username



name of this homeConfiguration{zwsp}.



__Type:__ string



__Default:__ ``{quot}config{zwsp}.networking{zwsp}.hostName{quot}``


