== artifacts{zwsp}.config{zwsp}.agenix{zwsp}.flakeStoreDir

Path reference where encrypted secrets are stored for agenix{zwsp}. This is used to to populate ``age{zwsp}.secrets``{zwsp}.



__Type:__ absolute path



__Example:__

----
{
  flakeStoreDir = inputs.my-secrets;
  flakeStoreDir = ./secrets;
};

----



== artifacts{zwsp}.config{zwsp}.agenix{zwsp}.machineName



name of this machine



__Type:__ string



__Default:__ ``{quot}config{zwsp}.networking{zwsp}.hostName{quot}``



== artifacts{zwsp}.config{zwsp}.agenix{zwsp}.publicHostKey



public key used to encrypt secrets for this host can be found via ``ssh-keyscan {zwsp}+<+{zwsp}host{gt}``



__Type:__ string



== artifacts{zwsp}.config{zwsp}.agenix{zwsp}.publicUserKeys



public key used to encrypt secrets for this host



__Type:__ list of string



__Default:__ ``{startsb} {endsb}``



== artifacts{zwsp}.config{zwsp}.agenix{zwsp}.storeDir



Path to the secrets store where agenix backend will serialize secrets to{zwsp}.



__Type:__ string



__Default:__ ``{quot}secrets{quot}``



__Example:__ ``{quot}$HOME/nixos-secrets{quot}``


